print("########################################")
print("#                                      #")
print("#           ___  ___  ___              #")
print("#          |__ \\|__ \\|__ \\             #")
print("#             ) |  ) |  ) |            #")
print("#            / /  / /  / /             #")
print("#           / /_ / /_ / /_             #")
print("#          |____|____|____|            #")
print("#                                      #")
print("#       Willkommen beim Taxirechner    #")
print("#                                      #")
print("########################################")
print("")
grund = input("was ist die grund paulschale? ")
kmkosten = input("wie viel kosted ein klometer? ")
kilometer = input("wie vile kilometer bist du gefaren? ")
summe = float(kmkosten) * float(kilometer) + float(grund)
print(f"es kostet {summe} euro. ")
print("")
input("enter druken ...")